### ISSUE TITLE
Improve website security

### ISSUE THREAD

**Issue by Sonicelo** [easyphp/easyphp-website#11]
Can you please update your website with https certificate? It will improve your ranking as well as authenticity. You need to do that for both the main domain and warehouse seperatly.

Depending on your host, there could be free certificates available or if you have your own server its easy to setup up using LetsEncrypt https://letsencrypt.org/.

If you need assistance with this, I can help with additional information.

**Comment by CyrilCharlier** [comment]
Good point !, i use Let's encrypt and it si perfect.

**Comment by easyphp** [comment]
Done!
