### ISSUE TITLE
Change login password

### ISSUE THREAD

**Issue by Sonicelo** [easyphp/easyphp-website#12]
Where can I change my password? Clearly I am missing the user account settings.

**Comment by CyrilCharlier** [comment]
you can't change yourself .. only admin can resend it :(

**Comment by Sonicelo** [comment]
Are you planing to update this? Its kind of a old school solution.

**Comment by CyrilCharlier** [comment]
i'm not "easyphp" only a final user
I lost my password and I had to ask for it again by email easyphpdotorg@gmail.com
