### ISSUE TITLE
unable to complete download

### ISSUE THREAD

**Issue by makap0120** [easyphp/easyphp-website#16]
It downloads all 60.9 out of 60.9 mbs, yet the scanning process of a file never ends. Tried both on Chrome and Edge. I'm quite sure there's an issue with your website, bcus files from other sources downloads as usual.

**Comment by nicefox1** [comment]
Me too. Hangs in chrome and edge (maybe something with it's antivirus scan?). It doesn't hang in firefox - use that.

**Comment by makap0120** [comment]
All it took was a pc restart, right after it download was successfully in all browsers.
