### ISSUE TITLE
Download Impossible

### ISSUE THREAD

**Issue by CyrilCharlier** [easyphp/easyphp-website#2]
When i want to download 16.1.1 i have this error : 

![2016-04-09_08h40_10](https://cloud.githubusercontent.com/assets/11455745/14402233/cf0af242-fe2e-11e5-915f-17bf84391aed.png)

**Comment by easyphp** [comment]
Thanks you! It's fixed.

**Comment by CyrilCharlier** [comment]
good thanks !
